stages:
  - unittest
  - build
  - env
  - deploy
variables:
  FLASKNAME: flask-$CI_COMMIT_REF_NAME
unit-test:
  stage: unittest
  image:
    name: python:3
  script:
    - pip install --no-cache-dir -r dockerfile/flask-api/requirements.txt
    - python dockerfile/flask-api/test.py
  tags:
    - vm2-k8s
build-and-push-flask:
  stage: build
  image:
    name: docker
  script:
    - docker version
    - docker build ./dockerfile/flask-api --tag demoyuw/flask-api:$CI_COMMIT_REF_NAME
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    - docker push demoyuw/flask-api:$CI_COMMIT_REF_NAME
  tags:
    - vm2-k8s
apply-flask-namespace:
  stage: env
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - mkdir .kube
    - echo $kubeconfig | base64 -d > ~/.kube/config
    - kubectl config get-contexts
    - sed -i "s/flask/$FLASKNAME/g" namespace/flask-ns.yaml
    - cat namespace/flask-ns.yaml
    - kubectl apply -f namespace/flask-ns.yaml
  tags:
    - vm2-k8s
apply-flask-deployment:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - mkdir .kube
    - echo $kubeconfig | base64 -d > ~/.kube/config
    - kubectl config get-contexts
    - sed -i "s/master/$CI_COMMIT_REF_NAME/g" deployment/flask-api/flask-api-deploy.yaml
    - cat deployment/flask-api/flask-api-deploy.yaml
    - kubectl apply -f deployment/flask-api/flask-api-deploy.yaml -n $FLASKNAME
  tags:
    - vm2-k8s
apply-flask-service:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - mkdir .kube
    - echo $kubeconfig | base64 -d > ~/.kube/config
    - kubectl config get-contexts
    - cat service/flask-service.yaml
    - kubectl apply -f service/flask-service.yaml -n $FLASKNAME
    - kubectl get service -n $FLASKNAME
  tags:
    - vm2-k8s
