stages:
#  - quality
  - build
  - run
  - test

before_script:
  - docker image ls
  - docker ps -a

#sonarqube_scan:
#  stage: quality
#  script:
#  - docker run -e SONAR_HOST_URL="http://10.138.0.2:9000" -e SONAR_LOGIN="admin" -e SONAR_PASSWORD="openstack" --rm -v "/home/demoyuw:/usr/src" sonarsource/sonar-scanner-cli ls


build-flask-image:
  stage: build
  script:
    - docker build ./dockerfile/flask-api --tag demoyuw/flask-api:$CI_COMMIT_REF_NAME
    - docker login -u demoyuw -p a0918101553
    - docker push demoyuw/flask-api:$CI_COMMIT_REF_NAME

run-flask-image:
  stage: run
  script:
    - docker rm -f flask-$CI_COMMIT_REF_NAME
    - docker run -d -P --name flask-$CI_COMMIT_REF_NAME demoyuw/flask-api:$CI_COMMIT_REF_NAME
  dependencies:
    - build-flask-image

test-flask-container:
  stage: test
  script:
    - docker exec -i flask-$CI_COMMIT_REF_NAME python test.py
  dependencies:
    - run-flask-image


after_script:
  - docker image ls
  - docker ps -a
