stages:
  - name: build sonarqube runner image
    steps:
    - publishImageConfig:
        dockerfilePath: ./sonarqube/sonar-runner/Dockerfile
        buildContext: .
        tag: devops-sonarrunner:${CICD_EXECUTION_SEQUENCE}
  - name: run sonarqube runner
    steps:
    - applyYamlConfig:
        path: ./sonarqube/sonar-runner/k8s-yaml/sonar-runner-deployment.yaml
  - name: Publish flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./flask/dockerfile/Dockerfile
        buildContext: .
        tag: demoyuw/devops-flask:${CICD_EXECUTION_SEQUENCE}
  - name: deploy dev flask-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./flask/k8s-yaml/Development/flask-deployment.yaml
    - applyYamlConfig:
        path: ./flask/k8s-yaml/Development/flask-service.yaml
    when:
      branch:
        exclude: [ master ]
  - name: deploy staging flask-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./flask/k8s-yaml/Staging/flask-deployment.yaml
    - applyYamlConfig:
        path: ./flask/k8s-yaml/Staging/flask-service.yaml
    when:
      branch:
        exclude: [ master ]
  - name: deploy production flask-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./flask/k8s-yaml/Production/flask-deployment.yaml
    - applyYamlConfig:
        path: ./flask/k8s-yaml/Production/flask-service.yaml
    when:
      branch: master
      event: [ push ]